scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost']

  - job_name: 'blackbox'
    metrics_path: /probe
    scrape_interval: 10s
    params:
      module: [http_2xx]
    static_configs:
      - targets: 
        - https://test123.kz
        - https://re-boot.kz
        - https://www.google.kz
        - https://www.google.com
        - localhost:8000
        - localhost:80
        - 127.0.0.11:8000
        - 127.0.0.11:80
        - http://nginx
        - http://nginx:80

  
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

rule_files:
  - "alerts.yml"
